#!/usr/bin/env python3
"""
FTTH GIS Schema Configuration — FiberHome Project 2
====================================================
Reconciled FTTH feature class schemas from 8 authoritative CSV specification files.

Reconciled Discrepancies (Trace D1-D7):
  D1: ZPM uses REF_SRO (NOT REF_PM) — confirmed by ZPM.shp reference data
  D2: BOITE.MODE_POSE has 3 values: Façade, Chambre, Aerien (not the 5-value CABLE list)
  D3: BOITE.TYPE = {BPE, PBO, BPI, PTO} (4 values; TS/GeoFormer add PTO beyond CSV's 3)
  D4: CSV CODE duplication errors in CABLE, PTECH, INFRASTRUCTURE — deduplicated
  D5: IMB.CODE_VOIE does NOT exist in layer schema — excluded from mandatory checks
  D6: INFRASTRUCTURE.TYPE uses SOUTERRAIN (CSV has typo SOUTEREAIN)
  D7: All domain values normalized to UPPERCASE for comparison

Shapefile reference: 10-char truncated field names.
GeoPackage reference: full field names.

Source documents:
  - /official/evaluation_standards/*.csv (authoritative field names, types, lengths, mandatory O/C/N)
  - FTTH_GIS_Technical_Standards.md Part II (descriptions, domain values)
  - GeoFormer_FiberHome_P2_AgentPrompts.md Agent 6 (schema binding, geometry enforcement)

CRS: EPSG:4326 (WGS84). Output format: GeoPackage (.gpkg).
QGIS display CRS: EPSG:3857 (OTF reprojection for OSM tiles).
"""

# ── Geometry type constants (use integers for cross-API portability) ──────────
WKB_POINT = 1
WKB_LINESTRING = 2
WKB_POLYGON = 3

# ── 1. REQUIRED LAYERS ────────────────────────────────────────────────────────

REQUIRED_LAYERS = {"BOITE", "CABLE", "PTECH", "INFRASTRUCTURE", "SITE", "ZNRO", "ZPM", "IMB"}

# ── 2. REQUIRED GEOMETRY TYPES ─────────────────────────────────────────────────

REQUIRED_GEOM = {
    "BOITE": WKB_POINT,
    "CABLE": WKB_LINESTRING,
    "PTECH": WKB_POINT,
    "INFRASTRUCTURE": WKB_LINESTRING,
    "SITE": WKB_POINT,
    "ZNRO": WKB_POLYGON,
    "ZPM": WKB_POLYGON,
    "IMB": WKB_POINT,  # Also accepts Polygon (building footprints)
}

REQUIRED_GEOM_NAMES = {
    "BOITE": "Point",
    "CABLE": "LineString",
    "PTECH": "Point",
    "INFRASTRUCTURE": "LineString",
    "SITE": "Point",
    "ZNRO": "Polygon",
    "ZPM": "Polygon",
    "IMB": "Point or Polygon",
}

# ── 3. SEVERITY CODES ──────────────────────────────────────────────────────────

SEVERITY = {
    "CRITICAL": "C",
    "ERROR": "E",
    "WARNING": "W",
}

# ── 4. FEATURE CLASS SCHEMAS ───────────────────────────────────────────────────
# Each FC dict:
#   fc_name, geometry_type, layer_name,
#   fields: [{name, full_name, truncated_name, type, length, mandatory, domain_values, description}]
#   mandatory_fields: [field names that must be non-null]
#   unique_fields: [field names that must be unique within the layer]
#
# Mandatory: O = Obligatoire (must be present and non-null)
#            C = Conditionally required (must be non-null if the data exists)
#            N = Not required (may be null/absent)

BOITE = {
    "fc_name": "BOITE",
    "geometry_type": "Point",
    "layer_name": "BOITE",
    "fields": [
        {
            "name": "CODE",
            "full_name": "CODE",
            "truncated_name": "CODE",
            "type": "Text",
            "length": 30,
            "mandatory": "O",
            "domain_values": None,
            "description": "Optical box code. Formats: BPE-{TrigramVille}-{QuartierNumPM}-{Increment}; PBO-...; BPI-...",
            "source": "CSV",
        },
        {
            "name": "CODE_PTC",
            "full_name": "CODE_PTC",
            "truncated_name": "CODE_PTC",
            "type": "Text",
            "length": 30,
            "mandatory": "O",
            "domain_values": None,
            "description": "Hosting PTECH code. Format: CHA-{NumChambre}",
            "source": "CSV",
        },
        {
            "name": "REF_PLAQUE",
            "full_name": "REF_PLAQUE",
            "truncated_name": "REF_PLAQUE",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "Panel reference. Format: {TrigramVille}-{Quartier}",
            "source": "CSV",
        },
        {
            "name": "REF_NRO",
            "full_name": "REF_NRO",
            "truncated_name": "REF_NRO",
            "type": "Text",
            "length": 50,
            "mandatory": "N",
            "domain_values": None,
            "description": "NRO reference. Format: UNF-NRO-{TrigramVille}-{Quartier}",
            "source": "CSV",
        },
        {
            "name": "REF_PM",
            "full_name": "REF_PM",
            "truncated_name": "REF_PM",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "PM reference. Format: {TrigramVille}-{QuartierNumPM}. FK → SITE.CODE (TYPE=PM)",
            "source": "CSV",
        },
        {
            "name": "TYPE",
            "full_name": "TYPE",
            "truncated_name": "TYPE",
            "type": "Text",
            "length": None,
            "mandatory": "O",
            "domain_values": ["BPE", "PBO", "BPI", "PTO"],
            "description": "Box type: BPE (floor splice), PBO (distribution box), BPI (building entry), PTO (optical terminal). D3: includes PTO beyond CSV's 3 values.",
            "source": "CSV+TS+GeoFormer",
        },
        {
            "name": "TYPE_STRUCTURE",
            "full_name": "TYPE_STRUCTURE",
            "truncated_name": "TYPE_STRUC",
            "type": "Text",
            "length": None,
            "mandatory": "N",
            "domain_values": ["TRANSPORT", "DISTRIBUTION"],
            "description": "Network structure: Transport or Distribution",
            "source": "CSV",
        },
        {
            "name": "MODE_POSE",
            "full_name": "MODE_POSE",
            "truncated_name": "MODE_POSE",
            "type": "Text",
            "length": 30,
            "mandatory": "O",
            "domain_values": ["FACADE", "CHAMBRE", "AERIEN"],
            "description": "Installation mode: Façade, Chambre, Aerien. D2: 3 values, NOT the 5-value CABLE.MODE_POSE list.",
            "source": "CSV",
        },
        {
            "name": "CAPACITE",
            "full_name": "CAPACITE",
            "truncated_name": "CAPACITE",
            "type": "Integer",
            "length": 3,
            "mandatory": "O",
            "domain_values": None,
            "description": "Total splice capacity (fibres). Positive integer.",
            "source": "CSV",
        },
        {
            "name": "NB_LOGEMENT",
            "full_name": "NB_LOGEMENT",
            "truncated_name": "NB_LOGEMEN",
            "type": "Integer",
            "length": 10,
            "mandatory": "N",
            "domain_values": None,
            "description": "Connectable households count.",
            "source": "CSV",
        },
        {
            "name": "NB_SPLICES",
            "full_name": "NB_SPLICES",
            "truncated_name": "NB_SPLICES",
            "type": "Integer",
            "length": None,
            "mandatory": "N",
            "domain_values": None,
            "description": "Splice count (>= 0).",
            "source": "CSV",
        },
        {
            "name": "NB_FIBRE_UTIL",
            "full_name": "NB_FIBRE_UTIL",
            "truncated_name": "NB_FIBRE_U",
            "type": "Integer",
            "length": 3,
            "mandatory": "O",
            "domain_values": None,
            "description": "Fibres (households + reserve). Must be ≤ CAPACITE for PBO (Rule 7.1).",
            "source": "CSV",
        },
        {
            "name": "FABRIQUANT",
            "full_name": "FABRIQUANT",
            "truncated_name": "FABRIQUANT",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "Manufacturer reference. E.g. FBR, FIBERHOME.",
            "source": "CSV",
        },
        {
            "name": "REF_BPE",
            "full_name": "REF_BPE",
            "truncated_name": "REF_BPE",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "Product reference. E.g. FBR-BPO24.",
            "source": "CSV",
        },
        {
            "name": "NB_CASSETTES_MAX",
            "full_name": "NB_CASSETTES_MAX",
            "truncated_name": "NB_CASSETT",
            "type": "Integer",
            "length": 3,
            "mandatory": "O",
            "domain_values": None,
            "description": "Max cassette capacity.",
            "source": "CSV",
        },
        {
            "name": "CABLE_AMONT",
            "full_name": "CABLE_AMONT",
            "truncated_name": "CABLE_AMON",
            "type": "Text",
            "length": 20,
            "mandatory": "O",
            "domain_values": None,
            "description": "Upstream cable reference. Format: CDI-UNF-{PM}-{Tiroir}-{Num}",
            "source": "CSV",
        },
        {
            "name": "STATUT",
            "full_name": "STATUT",
            "truncated_name": "STATUT",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": ["DEPLOYE", "EN COURS DE DEPLOIEMENT", "EN PROJET"],
            "description": "Deployment status.",
            "source": "CSV",
        },
        {
            "name": "PROPRIETAIRE",
            "full_name": "PROPRIETAIRE",
            "truncated_name": "PROPRIETAI",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "Owner. Typically UNIFIBER.",
            "source": "CSV",
        },
        {
            "name": "GESTIONNAIRE",
            "full_name": "GESTIONNAIRE",
            "truncated_name": "GESTIONNAI",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "Manager. Typically UNIFIBER.",
            "source": "CSV",
        },
        {
            "name": "ADRESSSE",
            "full_name": "ADRESSSE",
            "truncated_name": "ADRESSSE",
            "type": "Text",
            "length": 50,
            "mandatory": "C",
            "domain_values": None,
            "description": "Address near the box. Condition: if exists.",
            "source": "CSV",
        },
        {
            "name": "VILLE",
            "full_name": "VILLE",
            "truncated_name": "VILLE",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "City name.",
            "source": "CSV",
        },
        {
            "name": "CODE_POSTAL",
            "full_name": "CODE_POSTAL",
            "truncated_name": "CODE_POSTA",
            "type": "Integer",
            "length": 5,
            "mandatory": "C",
            "domain_values": None,
            "description": "Postal code. 5-digit integer. Condition: if exists.",
            "source": "CSV",
        },
        {
            "name": "X",
            "full_name": "X",
            "truncated_name": "X",
            "type": "Double",
            "length": None,
            "mandatory": "O",
            "domain_values": None,
            "description": "Longitude (WGS84, EPSG:4326). Computed from geometry centroid.",
            "source": "CSV",
        },
        {
            "name": "Y",
            "full_name": "Y",
            "truncated_name": "Y",
            "type": "Double",
            "length": None,
            "mandatory": "O",
            "domain_values": None,
            "description": "Latitude (WGS84, EPSG:4326). Computed from geometry centroid.",
            "source": "CSV",
        },
        {
            "name": "COMMENT",
            "full_name": "COMMENT",
            "truncated_name": "COMMENT",
            "type": "Text",
            "length": 50,
            "mandatory": "C",
            "domain_values": None,
            "description": "Comments.",
            "source": "CSV",
        },
    ],
    "mandatory_fields": [
        "CODE",
        "CODE_PTC",
        "REF_PLAQUE",
        "REF_PM",
        "TYPE",
        "MODE_POSE",
        "CAPACITE",
        "NB_FIBRE_UTIL",
        "FABRIQUANT",
        "REF_BPE",
        "NB_CASSETTES_MAX",
        "CABLE_AMONT",
        "STATUT",
        "PROPRIETAIRE",
        "GESTIONNAIRE",
        "VILLE",
        "X",
        "Y",
    ],
    "conditional_fields": ["REF_NRO", "ADRESSSE", "CODE_POSTAL", "COMMENT"],
    "unique_fields": ["CODE"],
}

CABLE = {
    "fc_name": "CABLE",
    "geometry_type": "LineString",
    "layer_name": "CABLE",
    "fields": [
        {
            "name": "CODE",
            "full_name": "CODE",
            "truncated_name": "CODE",
            "type": "Text",
            "length": 30,
            "mandatory": "O",
            "domain_values": None,
            "description": "Cable code. Format: CDI-UNF-{PM}-{Tiroir}-{Num}",
            "source": "CSV",
        },
        {
            "name": "NOM",
            "full_name": "NOM",
            "truncated_name": "NOM",
            "type": "Text",
            "length": 30,
            "mandatory": "C",
            "domain_values": None,
            "description": "Field name. Same as CODE if no field name exists.",
            "source": "CSV",
        },
        {
            "name": "REF_PLAQUE",
            "full_name": "REF_PLAQUE",
            "truncated_name": "REF_PLAQUE",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "Panel reference. Format: {TrigramVille}-{Quartier}",
            "source": "CSV",
        },
        {
            "name": "REF_NRO",
            "full_name": "REF_NRO",
            "truncated_name": "REF_NRO",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "NRO reference. Format: NRO-{TrigramVille}-{Quartier}",
            "source": "CSV",
        },
        {
            "name": "REF_PM",
            "full_name": "REF_PM",
            "truncated_name": "REF_PM",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "PM reference. Format: {TrigramVille}-{QuartierNumPM}. FK → SITE.CODE (TYPE=PM)",
            "source": "CSV",
        },
        {
            "name": "CODE_INFRA",
            "full_name": "CODE_INFRA",
            "truncated_name": "CODE_INFRA",
            "type": "Text",
            "length": 20,
            "mandatory": "O",
            "domain_values": None,
            "description": "Hosting infrastructure code. FK → INFRASTRUCTURE.CODE",
            "source": "CSV",
        },
        {
            "name": "ORIGINE",
            "full_name": "ORIGINE",
            "truncated_name": "ORIGINE",
            "type": "Text",
            "length": 20,
            "mandatory": "O",
            "domain_values": None,
            "description": "Upstream box/site code. FK → BOITE.CODE or SITE.CODE. Critical: ORIGINE ≠ EXTREMITE (Rule 6.6).",
            "source": "CSV",
        },
        {
            "name": "EXTREMITE",
            "full_name": "EXTREMITE",
            "truncated_name": "EXTREMITE",
            "type": "Text",
            "length": 20,
            "mandatory": "O",
            "domain_values": None,
            "description": "Downstream box/site code. FK → BOITE.CODE or SITE.CODE. Critical: ORIGINE ≠ EXTREMITE (Rule 6.6).",
            "source": "CSV",
        },
        {
            "name": "TYPE_CABLE",
            "full_name": "TYPE_CABLE",
            "truncated_name": "TYPE_CABLE",
            "type": "Text",
            "length": 15,
            "mandatory": "O",
            "domain_values": ["TRANSPORT", "DISTRIBUTION", "RACCORDEMENT", "VERTICALITE", "COLLECTE"],
            "description": "Cable type: TRANSPORT, DISTRIBUTION, RACCORDEMENT, VERTICALITE, COLLECTE",
            "source": "CSV",
        },
        {
            "name": "DIAMETRE",
            "full_name": "DIAMETRE",
            "truncated_name": "DIAMETRE",
            "type": "Integer",
            "length": 2,
            "mandatory": "O",
            "domain_values": None,
            "description": "Cable diameter in mm. Positive integer.",
            "source": "CSV",
        },
        {
            "name": "MODE_POSE",
            "full_name": "MODE_POSE",
            "truncated_name": "MODE_POSE",
            "type": "Text",
            "length": 30,
            "mandatory": "O",
            "domain_values": ["SOUTERRAIN", "AERIEN", "FACADE", "IMMEUBLE", "COLONNE MONTANTE"],
            "description": "Installation mode: SOUTERRAIN, AERIEN, FACADE, IMMEUBLE, COLONNE MONTANTE",
            "source": "CSV",
        },
        {
            "name": "CAPACITE",
            "full_name": "CAPACITE",
            "truncated_name": "CAPACITE",
            "type": "Integer",
            "length": 3,
            "mandatory": "O",
            "domain_values": None,
            "description": "Fibre capacity. Typical values: 2, 6, 12, 24, 36, 48, 72, 96, 144, ...",
            "source": "CSV",
        },
        {
            "name": "MODULO",
            "full_name": "MODULO",
            "truncated_name": "MODULO",
            "type": "Integer",
            "length": 2,
            "mandatory": "O",
            "domain_values": None,
            "description": "Cable modularity. Typical values: 2, 6, 12.",
            "source": "CSV",
        },
        {
            "name": "FABRIQUANT",
            "full_name": "FABRIQUANT",
            "truncated_name": "FABRIQUANT",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "Manufacturer. E.g. FBR, FIBERHOME.",
            "source": "CSV",
        },
        {
            "name": "REF_PRODUIT",
            "full_name": "REF_PRODUIT",
            "truncated_name": "REF_PRODUI",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "Product reference.",
            "source": "CSV",
        },
        {
            "name": "TYPE_FIBRE",
            "full_name": "TYPE_FIBRE",
            "truncated_name": "TYPE_FIBRE",
            "type": "Text",
            "length": 10,
            "mandatory": "N",
            "domain_values": [
                "G652", "G652A", "G652B", "G652C", "G652D",
                "G657", "G657A", "G657A1", "G657A2", "G657A3",
                "G657B", "G657B1", "G657B2", "G657B3",
            ],
            "description": "Fibre type per ITU-T G.65x series.",
            "source": "CSV",
        },
        {
            "name": "NB_FIBRE_UTIL",
            "full_name": "NB_FIBRE_UTIL",
            "truncated_name": "NB_FIBRE_U",
            "type": "Integer",
            "length": 3,
            "mandatory": "O",
            "domain_values": None,
            "description": "Fibres used. Must be ≤ CAPACITE.",
            "source": "CSV",
        },
        {
            "name": "NB_FIBRE_DISP",
            "full_name": "NB_FIBRE_DISP",
            "truncated_name": "NB_FIBRE_D",
            "type": "Integer",
            "length": 3,
            "mandatory": "O",
            "domain_values": None,
            "description": "Fibres available. Should equal CAPACITE - NB_FIBRE_UTIL.",
            "source": "CSV",
        },
        {
            "name": "STATUT",
            "full_name": "STATUT",
            "truncated_name": "STATUT",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": ["DEPLOYE", "EN COURS DE DEPLOIEMENT", "EN PROJET"],
            "description": "Deployment status.",
            "source": "CSV",
        },
        {
            "name": "PROPRIETAIRE",
            "full_name": "PROPRIETAIRE",
            "truncated_name": "PROPRIETAI",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "Owner.",
            "source": "CSV",
        },
        {
            "name": "GESTIONNAIRE",
            "full_name": "GESTIONNAIRE",
            "truncated_name": "GESTIONNAI",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "Manager.",
            "source": "CSV",
        },
        {
            "name": "TYPE_PROP",
            "full_name": "TYPE_PROP",
            "truncated_name": "TYPE_PROP",
            "type": "Text",
            "length": 30,
            "mandatory": "N",
            "domain_values": None,
            "description": "Property type. e.g. Construction.",
            "source": "CSV",
        },
        {
            "name": "LONGUEUR",
            "full_name": "LONGUEUR",
            "truncated_name": "LONGUEUR",
            "type": "Double",
            "length": 10,
            "mandatory": "O",
            "domain_values": None,
            "description": "Cable length in metres (haversine over projected CRS).",
            "source": "CSV",
        },
        {
            "name": "COMMENT",
            "full_name": "COMMENT",
            "truncated_name": "COMMENT",
            "type": "Text",
            "length": 50,
            "mandatory": "C",
            "domain_values": None,
            "description": "Comments.",
            "source": "CSV",
        },
    ],
    "mandatory_fields": [
        "CODE",
        "REF_PLAQUE",
        "REF_NRO",
        "REF_PM",
        "CODE_INFRA",
        "ORIGINE",
        "EXTREMITE",
        "TYPE_CABLE",
        "DIAMETRE",
        "MODE_POSE",
        "CAPACITE",
        "MODULO",
        "FABRIQUANT",
        "REF_PRODUIT",
        "NB_FIBRE_UTIL",
        "NB_FIBRE_DISP",
        "STATUT",
        "PROPRIETAIRE",
        "GESTIONNAIRE",
        "LONGUEUR",
    ],
    "conditional_fields": ["NOM", "TYPE_FIBRE", "TYPE_PROP", "COMMENT"],
    "unique_fields": ["CODE"],
}

PTECH = {
    "fc_name": "PTECH",
    "geometry_type": "Point",
    "layer_name": "PTECH",
    "fields": [
        {
            "name": "CODE",
            "full_name": "CODE",
            "truncated_name": "CODE",
            "type": "Text",
            "length": 30,
            "mandatory": "O",
            "domain_values": None,
            "description": "Technical point identifier. Format: IAM-POT-00001",
            "source": "CSV",
        },
        {
            "name": "NOM",
            "full_name": "NOM",
            "truncated_name": "NOM",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "Technical point name. Same as CODE if UNIFIBER point, empty if no name.",
            "source": "CSV",
        },
        {
            "name": "REF_PLAQUE",
            "full_name": "REF_PLAQUE",
            "truncated_name": "REF_PLAQUE",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "Panel reference.",
            "source": "CSV",
        },
        {
            "name": "TYPE",
            "full_name": "TYPE",
            "truncated_name": "TYPE",
            "type": "Text",
            "length": 30,
            "mandatory": "O",
            "domain_values": ["APPUI", "CHAMBRE", "ANCRAGE FACADE", "IMMEUBLE", "AUTRE"],
            "description": "Technical point type: APPUI (pole), CHAMBRE (chamber), ANCRAGE FACADE (facade anchor), IMMEUBLE (building), AUTRE",
            "source": "CSV+TS",
        },
        {
            "name": "NATURE",
            "full_name": "NATURE",
            "truncated_name": "NATURE",
            "type": "Text",
            "length": 30,
            "mandatory": "O",
            "domain_values": None,
            "description": "Technical point nature. E.g. PBOI, L2T, PNS3, A1-A18 series, B1-B4, C1-C4, D1-D3.",
            "source": "CSV",
        },
        {
            "name": "HAUTEUR_APPUI",
            "full_name": "HAUTEUR_APPUI",
            "truncated_name": "HAUTEUR_AP",
            "type": "Double",
            "length": 10,
            "mandatory": "C",
            "domain_values": None,
            "description": "Support height in metres. Condition: if TYPE=APPUI (pole); 0 otherwise.",
            "source": "CSV",
        },
        {
            "name": "TYPE_APPUI",
            "full_name": "TYPE_APPUI",
            "truncated_name": "TYPE_APPUI",
            "type": "Double",
            "length": 10,
            "mandatory": "C",
            "domain_values": None,
            "description": "Support type: Simple, Moisé, Haubané, Couple. Condition: if TYPE=APPUI.",
            "source": "CSV",
        },
        {
            "name": "EFFORT_APPUI",
            "full_name": "EFFORT_APPUI",
            "truncated_name": "EFFORT_APP",
            "type": "Double",
            "length": 10,
            "mandatory": "O",
            "domain_values": None,
            "description": "Nominal force in daN. Required if TYPE=APPUI; empty otherwise.",
            "source": "CSV",
        },
        {
            "name": "NB_BOITIERS",
            "full_name": "NB_BOITIERS",
            "truncated_name": "NB_BOITIER",
            "type": "Integer",
            "length": None,
            "mandatory": "N",
            "domain_values": None,
            "description": "Box count at this technical point (>= 0).",
            "source": "CSV",
        },
        {
            "name": "STATUT",
            "full_name": "STATUT",
            "truncated_name": "STATUT",
            "type": "Text",
            "length": 30,
            "mandatory": "O",
            "domain_values": ["DEPLOYE", "EN COURS DE DEPLOIEMENT", "EN PROJET"],
            "description": "Deployment status.",
            "source": "CSV",
        },
        {
            "name": "PROPRIETAIRE",
            "full_name": "PROPRIETAIRE",
            "truncated_name": "PROPRIETAI",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "Owner. Typically UNIFIBER.",
            "source": "CSV",
        },
        {
            "name": "GESTIONNAIRE",
            "full_name": "GESTIONNAIRE",
            "truncated_name": "GESTIONNAI",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "Manager. Typically UNIFIBER.",
            "source": "CSV",
        },
        {
            "name": "ADRESSSE",
            "full_name": "ADRESSSE",
            "truncated_name": "ADRESSSE",
            "type": "Text",
            "length": 50,
            "mandatory": "C",
            "domain_values": None,
            "description": "Address near the point. Condition: if exists.",
            "source": "CSV",
        },
        {
            "name": "VILLE",
            "full_name": "VILLE",
            "truncated_name": "VILLE",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "City name.",
            "source": "CSV",
        },
        {
            "name": "CODE_POSTAL",
            "full_name": "CODE_POSTAL",
            "truncated_name": "CODE_POSTA",
            "type": "Integer",
            "length": 5,
            "mandatory": "C",
            "domain_values": None,
            "description": "Postal code. 5-digit integer. Condition: if exists.",
            "source": "CSV",
        },
        {
            "name": "X",
            "full_name": "X",
            "truncated_name": "X",
            "type": "Double",
            "length": None,
            "mandatory": "O",
            "domain_values": None,
            "description": "Longitude (WGS84, EPSG:4326). Computed from geometry.",
            "source": "CSV",
        },
        {
            "name": "Y",
            "full_name": "Y",
            "truncated_name": "Y",
            "type": "Double",
            "length": None,
            "mandatory": "O",
            "domain_values": None,
            "description": "Latitude (WGS84, EPSG:4326). Computed from geometry.",
            "source": "CSV",
        },
        {
            "name": "COMMENT",
            "full_name": "COMMENT",
            "truncated_name": "COMMENT",
            "type": "Text",
            "length": 50,
            "mandatory": "C",
            "domain_values": None,
            "description": "Comments.",
            "source": "CSV",
        },
    ],
    "mandatory_fields": [
        "CODE",
        "REF_PLAQUE",
        "TYPE",
        "NATURE",
        "EFFORT_APPUI",
        "STATUT",
        "PROPRIETAIRE",
        "GESTIONNAIRE",
        "VILLE",
        "X",
        "Y",
    ],
    "conditional_fields": ["HAUTEUR_APPUI", "TYPE_APPUI", "ADRESSSE", "CODE_POSTAL", "COMMENT"],
    "unique_fields": ["CODE"],
}

INFRASTRUCTURE_FC = {
    "fc_name": "INFRASTRUCTURE",
    "geometry_type": "LineString",
    "layer_name": "INFRASTRUCTURE",
    "fields": [
        {
            "name": "CODE",
            "full_name": "CODE",
            "truncated_name": "CODE",
            "type": "Text",
            "length": 30,
            "mandatory": "O",
            "domain_values": None,
            "description": "Infrastructure code. Format: UNF-INF-123456",
            "source": "CSV",
        },
        {
            "name": "NOM",
            "full_name": "NOM",
            "truncated_name": "NOM",
            "type": "Text",
            "length": 30,
            "mandatory": "C",
            "domain_values": None,
            "description": "Field name. Same as CODE if no field name.",
            "source": "CSV",
        },
        {
            "name": "REF_PLAQUE",
            "full_name": "REF_PLAQUE",
            "truncated_name": "REF_PLAQUE",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "Panel reference.",
            "source": "CSV",
        },
        {
            "name": "ORIGINE",
            "full_name": "ORIGINE",
            "truncated_name": "ORIGINE",
            "type": "Text",
            "length": 50,
            "mandatory": "N",
            "domain_values": None,
            "description": "Origin PTECH code. FK → PTECH.CODE",
            "source": "CSV",
        },
        {
            "name": "EXTREMITE",
            "full_name": "EXTREMITE",
            "truncated_name": "EXTREMITE",
            "type": "Text",
            "length": 50,
            "mandatory": "N",
            "domain_values": None,
            "description": "End PTECH code. FK → PTECH.CODE",
            "source": "CSV",
        },
        {
            "name": "COMPOSITION",
            "full_name": "COMPOSITION",
            "truncated_name": "COMPOSITI",
            "type": "Text",
            "length": 50,
            "mandatory": "C",
            "domain_values": None,
            "description": "Duct composition. Format: {N} {TYPE} {Diam} sep. '|'. Condition: if conduit.",
            "source": "CSV",
        },
        {
            "name": "TYPE",
            "full_name": "TYPE",
            "truncated_name": "TYPE",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": ["AERIEN", "SOUTERRAIN"],
            "description": "Physical infrastructure type: AERIEN or SOUTERRAIN. D6: SOUTERRAIN (not CSV typo SOUTEREAIN).",
            "source": "CSV",
        },
        {
            "name": "TYPE_LOG",
            "full_name": "TYPE_LOG",
            "truncated_name": "TYPE_LOG",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": ["TRANSPORT", "DISTRIBUTION", "RACCORDEMENT"],
            "description": "Logical infrastructure type: TRANSPORT, DISTRIBUTION, RACCORDEMENT",
            "source": "CSV",
        },
        {
            "name": "STATUT",
            "full_name": "STATUT",
            "truncated_name": "STATUT",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": ["DEPLOYE", "EN COURS DE DEPLOIEMENT", "EN PROJET"],
            "description": "Deployment status.",
            "source": "CSV",
        },
        {
            "name": "PROPRIETAIRE",
            "full_name": "PROPRIETAIRE",
            "truncated_name": "PROPRIETAI",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "Owner. Typically UNIFIBER.",
            "source": "CSV",
        },
        {
            "name": "GESTIONNAIRE",
            "full_name": "GESTIONNAIRE",
            "truncated_name": "GESTIONNAI",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "Manager. Typically UNIFIBER.",
            "source": "CSV",
        },
        {
            "name": "LONGUEUR",
            "full_name": "LONGUEUR",
            "truncated_name": "LONGUEUR",
            "type": "Double",
            "length": 10,
            "mandatory": "O",
            "domain_values": None,
            "description": "Length in metres (haversine over projected CRS).",
            "source": "CSV",
        },
        {
            "name": "COMMENT",
            "full_name": "COMMENT",
            "truncated_name": "COMMENT",
            "type": "Text",
            "length": 50,
            "mandatory": "C",
            "domain_values": None,
            "description": "Comments.",
            "source": "CSV",
        },
    ],
    "mandatory_fields": [
        "CODE",
        "REF_PLAQUE",
        "TYPE",
        "TYPE_LOG",
        "STATUT",
        "PROPRIETAIRE",
        "GESTIONNAIRE",
        "LONGUEUR",
    ],
    "conditional_fields": ["NOM", "ORIGINE", "EXTREMITE", "COMPOSITION", "COMMENT"],
    "unique_fields": ["CODE"],
}

SITE = {
    "fc_name": "SITE",
    "geometry_type": "Point",
    "layer_name": "SITE",
    "fields": [
        {
            "name": "CODE",
            "full_name": "CODE",
            "truncated_name": "CODE",
            "type": "Text",
            "length": 20,
            "mandatory": "O",
            "domain_values": None,
            "description": "Technical site code. Format: TNG01-BOK01",
            "source": "CSV",
        },
        {
            "name": "REF_PLAQUE",
            "full_name": "REF_PLAQUE",
            "truncated_name": "REF_PLAQUE",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "Panel reference.",
            "source": "CSV",
        },
        {
            "name": "REF_NRO",
            "full_name": "REF_NRO",
            "truncated_name": "REF_NRO",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "NRO reference. Format: UNF-NRO-{TrigramVille}-{Quartier}. FK → ZNRO.REF_NRO",
            "source": "CSV",
        },
        {
            "name": "TYPE",
            "full_name": "TYPE",
            "truncated_name": "TYPE",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": ["NRO", "PM", "ARMOIRE DE RUE", "BATIMENT", "LOCAL TECHNIQUE", "SHELTER"],
            "description": "Site type: NRO, PM, ARMOIRE DE RUE, BATIMENT, LOCAL TECHNIQUE, SHELTER",
            "source": "CSV+TS",
        },
        {
            "name": "FABRIQUANT",
            "full_name": "FABRIQUANT",
            "truncated_name": "FABRIQUANT",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "Manufacturer. E.g. FBR, FIBERHOME.",
            "source": "CSV",
        },
        {
            "name": "REF_PRODUIT",
            "full_name": "REF_PRODUIT",
            "truncated_name": "REF_PRODUI",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "Product reference. E.g. ADR_28U.",
            "source": "CSV",
        },
        {
            "name": "MODE_POSE",
            "full_name": "MODE_POSE",
            "truncated_name": "MODE_POSE",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "Site installation mode. PM by default; see l_site_type_phy.",
            "source": "CSV",
        },
        {
            "name": "STATUT",
            "full_name": "STATUT",
            "truncated_name": "STATUT",
            "type": "Text",
            "length": 30,
            "mandatory": "O",
            "domain_values": ["DEPLOYE", "EN COURS DE DEPLOIEMENT", "EN PROJET"],
            "description": "Deployment status.",
            "source": "CSV",
        },
        {
            "name": "PROPRIETAIRE",
            "full_name": "PROPRIETAIRE",
            "truncated_name": "PROPRIETAI",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "Owner.",
            "source": "CSV",
        },
        {
            "name": "GESTIONNAIRE",
            "full_name": "GESTIONNAIRE",
            "truncated_name": "GESTIONNAI",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "Manager.",
            "source": "CSV",
        },
        {
            "name": "ADRESSSE",
            "full_name": "ADRESSSE",
            "truncated_name": "ADRESSSE",
            "type": "Text",
            "length": 50,
            "mandatory": "C",
            "domain_values": None,
            "description": "Address near site. Condition: if exists.",
            "source": "CSV",
        },
        {
            "name": "COMMUNE",
            "full_name": "COMMUNE",
            "truncated_name": "COMMUNE",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "Municipality name.",
            "source": "CSV",
        },
        {
            "name": "CODE_POSTAL",
            "full_name": "CODE_POSTAL",
            "truncated_name": "CODE_POSTA",
            "type": "Integer",
            "length": 5,
            "mandatory": "C",
            "domain_values": None,
            "description": "Postal code. 5-digit integer. Condition: if exists.",
            "source": "CSV",
        },
        {
            "name": "X",
            "full_name": "X",
            "truncated_name": "X",
            "type": "Double",
            "length": None,
            "mandatory": "O",
            "domain_values": None,
            "description": "Longitude (WGS84, EPSG:4326). Computed from geometry.",
            "source": "CSV",
        },
        {
            "name": "Y",
            "full_name": "Y",
            "truncated_name": "Y",
            "type": "Double",
            "length": None,
            "mandatory": "O",
            "domain_values": None,
            "description": "Latitude (WGS84, EPSG:4326). Computed from geometry.",
            "source": "CSV",
        },
        {
            "name": "COMMENT",
            "full_name": "COMMENT",
            "truncated_name": "COMMENT",
            "type": "Text",
            "length": 50,
            "mandatory": "C",
            "domain_values": None,
            "description": "Comments.",
            "source": "CSV",
        },
    ],
    "mandatory_fields": [
        "CODE",
        "REF_PLAQUE",
        "REF_NRO",
        "TYPE",
        "FABRIQUANT",
        "REF_PRODUIT",
        "MODE_POSE",
        "STATUT",
        "PROPRIETAIRE",
        "GESTIONNAIRE",
        "COMMUNE",
        "X",
        "Y",
    ],
    "conditional_fields": ["ADRESSSE", "CODE_POSTAL", "COMMENT"],
    "unique_fields": ["CODE"],
}

ZNRO = {
    "fc_name": "ZNRO",
    "geometry_type": "Polygon",
    "layer_name": "ZNRO",
    "fields": [
        {
            "name": "CODE",
            "full_name": "CODE",
            "truncated_name": "CODE",
            "type": "Text",
            "length": 30,
            "mandatory": "O",
            "domain_values": None,
            "description": "Deployment zone code. Format: TNG01-BOK01",
            "source": "CSV",
        },
        {
            "name": "REF_PLAQUE",
            "full_name": "REF_PLAQUE",
            "truncated_name": "REF_PLAQUE",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "Panel reference.",
            "source": "CSV",
        },
        {
            "name": "REF_NRO",
            "full_name": "REF_NRO",
            "truncated_name": "REF_NRO",
            "type": "Text",
            "length": 30,
            "mandatory": "O",
            "domain_values": None,
            "description": "NRO name. Format: NRO-{TrigramVille}-{Quartier}",
            "source": "CSV",
        },
        {
            "name": "STATUT",
            "full_name": "STATUT",
            "truncated_name": "STATUT",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": ["DEPLOYE", "EN COURS DE DEPLOIEMENT", "EN PROJET"],
            "description": "Deployment status.",
            "source": "CSV",
        },
        {
            "name": "NB_PRISES",
            "full_name": "NB_PRISES",
            "truncated_name": "NB_PRISES",
            "type": "Integer",
            "length": 10,
            "mandatory": "O",
            "domain_values": None,
            "description": "Total port count. Positive integer.",
            "source": "CSV",
        },
        {
            "name": "COMMENT",
            "full_name": "COMMENT",
            "truncated_name": "COMMENT",
            "type": "Text",
            "length": 50,
            "mandatory": "C",
            "domain_values": None,
            "description": "Comments.",
            "source": "CSV",
        },
    ],
    "mandatory_fields": [
        "CODE",
        "REF_PLAQUE",
        "REF_NRO",
        "STATUT",
        "NB_PRISES",
    ],
    "conditional_fields": ["COMMENT"],
    "unique_fields": ["CODE"],
}

ZPM = {
    "fc_name": "ZPM",
    "geometry_type": "Polygon",
    "layer_name": "ZPM",
    "fields": [
        {
            "name": "CODE",
            "full_name": "CODE",
            "truncated_name": "CODE",
            "type": "Text",
            "length": 30,
            "mandatory": "O",
            "domain_values": None,
            "description": "Deployment zone code. Format: TNG01-BOK01",
            "source": "CSV",
        },
        {
            "name": "REF_PLAQUE",
            "full_name": "REF_PLAQUE",
            "truncated_name": "REF_PLAQUE",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "Panel reference.",
            "source": "CSV",
        },
        {
            "name": "REF_NRO",
            "full_name": "REF_NRO",
            "truncated_name": "REF_NRO",
            "type": "Text",
            "length": 30,
            "mandatory": "O",
            "domain_values": None,
            "description": "NRO name. Format: NRO-{TrigramVille}-{Quartier}. FK → ZNRO.REF_NRO",
            "source": "CSV",
        },
        {
            "name": "REF_SRO",
            "full_name": "REF_SRO",
            "truncated_name": "REF_SRO",
            "type": "Text",
            "length": 30,
            "mandatory": "O",
            "domain_values": None,
            "description": "PM name. D1: This field is REF_SRO NOT REF_PM. Format: TNG01-BOK01.",
            "source": "CSV (authoritative: ZPM.shp reference)",
        },
        {
            "name": "STATUT",
            "full_name": "STATUT",
            "truncated_name": "STATUT",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": ["DEPLOYE", "EN COURS DE DEPLOIEMENT", "EN PROJET"],
            "description": "Deployment status.",
            "source": "CSV",
        },
        {
            "name": "NB_PRISES",
            "full_name": "NB_PRISES",
            "truncated_name": "NB_PRISES",
            "type": "Integer",
            "length": 10,
            "mandatory": "O",
            "domain_values": None,
            "description": "Total housing unit count. Positive integer.",
            "source": "CSV",
        },
        {
            "name": "COMMENT",
            "full_name": "COMMENT",
            "truncated_name": "COMMENT",
            "type": "Text",
            "length": 50,
            "mandatory": "C",
            "domain_values": None,
            "description": "Comments.",
            "source": "CSV",
        },
    ],
    "mandatory_fields": [
        "CODE",
        "REF_PLAQUE",
        "REF_NRO",
        "REF_SRO",
        "STATUT",
        "NB_PRISES",
    ],
    "conditional_fields": ["COMMENT"],
    "unique_fields": ["CODE"],
}

IMB = {
    "fc_name": "IMB",
    "geometry_type": "Point or Polygon",
    "layer_name": "IMB",
    "fields": [
        {
            "name": "CODE",
            "full_name": "CODE",
            "truncated_name": "CODE",
            "type": "Text",
            "length": 30,
            "mandatory": "O",
            "domain_values": None,
            "description": "Building/served premise code.",
            "source": "TS+GeoFormer",
        },
        {
            "name": "REF_PLAQUE",
            "full_name": "REF_PLAQUE",
            "truncated_name": "REF_PLAQUE",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "Panel reference.",
            "source": "TS+GeoFormer",
        },
        {
            "name": "REGION",
            "full_name": "REGION",
            "truncated_name": "REGION",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "Region name.",
            "source": "TS",
        },
        {
            "name": "PROVINCE",
            "full_name": "PROVINCE",
            "truncated_name": "PROVINCE",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "Province name.",
            "source": "TS",
        },
        {
            "name": "VILLE",
            "full_name": "VILLE",
            "truncated_name": "VILLE",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "City name.",
            "source": "TS",
        },
        {
            "name": "COMMUNE",
            "full_name": "COMMUNE",
            "truncated_name": "COMMUNE",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": None,
            "description": "Municipality name.",
            "source": "TS",
        },
        {
            "name": "CODE_POSTAL",
            "full_name": "CODE_POSTAL",
            "truncated_name": "CODE_POSTA",
            "type": "Integer",
            "length": 5,
            "mandatory": "O",
            "domain_values": None,
            "description": "Postal code. 5-digit integer. Truncated to CODE_POSTA in Shapefile.",
            "source": "TS",
        },
        {
            "name": "NUMERO_VOIE",
            "full_name": "NUMERO_VOIE",
            "truncated_name": "NUMERO_VOI",
            "type": "Integer",
            "length": None,
            "mandatory": "O",
            "domain_values": None,
            "description": "Street number. Truncated to NUMERO_VOI in Shapefile.",
            "source": "TS",
        },
        {
            "name": "TYPE_VOIE",
            "full_name": "TYPE_VOIE",
            "truncated_name": "TYPE_VOIE",
            "type": "Text",
            "length": 30,
            "mandatory": "O",
            "domain_values": None,
            "description": "Street type (RUE, AVENUE, BOULEVARD, etc.).",
            "source": "TS",
        },
        {
            "name": "TYPE_BATIMENT",
            "full_name": "TYPE_BATIMENT",
            "truncated_name": "TYPE_BATIM",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": [
                "VILLA", "BATIMENT", "BATIMENT R+1", "BATIMENT R+2", "BATIMENT R+3",
                "IMMEUBLE", "IMMEUBLE COLLECTIF", "COMMERCE", "ENTREPOT", "ENTREPRISE",
                "USINE", "BATIMENT PUBLIC", "BATIMENT RELIGIEUX", "EQUIPEMENT SPORTIF",
                "ETABLISSEMENT PRIVE", "EXPLOITATION AGRICOLE", "EOLIENNE",
                "POSTE ELECTRIQUE", "PYLONE", "STATION METEO", "STATION POMPAGE",
            ],
            "description": "Building type per l_imb_bat domain (22 values). Truncated to TYPE_BATIM in Shapefile.",
            "source": "TS",
        },
        {
            "name": "TYPE_CLIENT",
            "full_name": "TYPE_CLIENT",
            "truncated_name": "TYPE_CLIEN",
            "type": "Text",
            "length": 30,
            "mandatory": "O",
            "domain_values": ["RESIDENTIEL", "PROFESSIONNEL", "ADMINISTRATION", "ENTREPRISE", "OPERATEUR"],
            "description": "Client type: RESIDENTIEL, PROFESSIONNEL, ADMINISTRATION, ENTREPRISE, OPERATEUR",
            "source": "TS",
        },
        {
            "name": "NB_LOC_RES",
            "full_name": "NB_LOC_RES",
            "truncated_name": "NB_LOC_RES",
            "type": "Integer",
            "length": None,
            "mandatory": "O",
            "domain_values": None,
            "description": "Number of residential units.",
            "source": "TS",
        },
        {
            "name": "NB_LOC_PRO",
            "full_name": "NB_LOC_PRO",
            "truncated_name": "NB_LOC_PRO",
            "type": "Integer",
            "length": None,
            "mandatory": "O",
            "domain_values": None,
            "description": "Number of professional units.",
            "source": "TS",
        },
        {
            "name": "NB_LOC_TOT",
            "full_name": "NB_LOC_TOT",
            "truncated_name": "NB_LOC_TOT",
            "type": "Integer",
            "length": None,
            "mandatory": "O",
            "domain_values": None,
            "description": "Total number of units (res + pro).",
            "source": "TS",
        },
        {
            "name": "RACCORDEMENT",
            "full_name": "RACCORDEMENT",
            "truncated_name": "RACCORDEME",
            "type": "Text",
            "length": 30,
            "mandatory": "O",
            "domain_values": ["SOUTERRAIN", "FACADE", "AERIEN", "COLONNE MONTANTE"],
            "description": "Building connection mode. Truncated to RACCORDEME in Shapefile.",
            "source": "TS",
        },
        {
            "name": "STATUT",
            "full_name": "STATUT",
            "truncated_name": "STATUT",
            "type": "Text",
            "length": 50,
            "mandatory": "O",
            "domain_values": ["DEPLOYE", "EN COURS DE DEPLOIEMENT", "EN PROJET"],
            "description": "Deployment status.",
            "source": "TS",
        },
        {
            "name": "NB_ETAGE",
            "full_name": "NB_ETAGE",
            "truncated_name": "NB_ETAGE",
            "type": "Integer",
            "length": None,
            "mandatory": "O",
            "domain_values": None,
            "description": "Number of floors.",
            "source": "TS",
        },
        {
            "name": "COL_MONTANTE",
            "full_name": "COL_MONTANTE",
            "truncated_name": "COL_MONTAN",
            "type": "Text",
            "length": 10,
            "mandatory": "O",
            "domain_values": None,
            "description": "Riser column presence (OUI/NON or Y/N). Truncated to COL_MONTAN in Shapefile.",
            "source": "TS",
        },
        {
            "name": "SOUS_SOL",
            "full_name": "SOUS_SOL",
            "truncated_name": "SOUS_SOL",
            "type": "Text",
            "length": 10,
            "mandatory": "O",
            "domain_values": None,
            "description": "Basement presence (OUI/NON or Y/N).",
            "source": "TS",
        },
        {
            "name": "SOUS_SOL_COMMUN",
            "full_name": "SOUS_SOL_COMMUN",
            "truncated_name": "SOUS_SOL_C",
            "type": "Text",
            "length": 10,
            "mandatory": "O",
            "domain_values": None,
            "description": "Shared basement presence (OUI/NON or Y/N). Truncated to SOUS_SOL_C in Shapefile.",
            "source": "TS",
        },
        {
            "name": "BPE_CODE",
            "full_name": "BPE_CODE",
            "truncated_name": "BPE_CODE",
            "type": "Text",
            "length": 30,
            "mandatory": "O",
            "domain_values": None,
            "description": "Associated BPE box code. FK → BOITE.CODE (TYPE=BPE).",
            "source": "TS",
        },
        {
            "name": "X",
            "full_name": "X",
            "truncated_name": "X",
            "type": "Double",
            "length": None,
            "mandatory": "O",
            "domain_values": None,
            "description": "Longitude (WGS84, EPSG:4326). Computed from geometry centroid.",
            "source": "TS",
        },
        {
            "name": "Y",
            "full_name": "Y",
            "truncated_name": "Y",
            "type": "Double",
            "length": None,
            "mandatory": "O",
            "domain_values": None,
            "description": "Latitude (WGS84, EPSG:4326). Computed from geometry centroid.",
            "source": "TS",
        },
    ],
    "mandatory_fields": [
        "CODE",
        "REF_PLAQUE",
        "REGION",
        "PROVINCE",
        "VILLE",
        "COMMUNE",
        "CODE_POSTAL",
        "NUMERO_VOIE",
        "TYPE_VOIE",
        "TYPE_BATIMENT",
        "TYPE_CLIENT",
        "NB_LOC_RES",
        "NB_LOC_PRO",
        "NB_LOC_TOT",
        "RACCORDEMENT",
        "STATUT",
        "NB_ETAGE",
        "COL_MONTANTE",
        "SOUS_SOL",
        "SOUS_SOL_COMMUN",
        "BPE_CODE",
        "X",
        "Y",
    ],
    "conditional_fields": [],
    "unique_fields": ["CODE"],
}

# ── Aggregated feature class list ─────────────────────────────────────────────

FEATURE_CLASSES = [BOITE, CABLE, PTECH, INFRASTRUCTURE_FC, SITE, ZNRO, ZPM, IMB]

FEATURE_CLASS_BY_NAME = {
    "BOITE": BOITE,
    "CABLE": CABLE,
    "PTECH": PTECH,
    "INFRASTRUCTURE": INFRASTRUCTURE_FC,
    "SITE": SITE,
    "ZNRO": ZNRO,
    "ZPM": ZPM,
    "IMB": IMB,
}

# ── 5. FIELD NAME CROSSWALK ───────────────────────────────────────────────────
# Maps truncated (10-char) Shapefile names → full field names for ALL layers.
# Shapefile truncation: names > 10 chars get first 10 chars only.

FIELD_NAME_CROSSWALK = {
    # BOITE truncations
    "TYPE_STRUC": "TYPE_STRUCTURE",
    "NB_LOGEMEN": "NB_LOGEMENT",
    "NB_FIBRE_U": "NB_FIBRE_UTIL",
    "NB_CASSETT": "NB_CASSETTES_MAX",
    "CABLE_AMON": "CABLE_AMONT",
    "PROPRIETAI": "PROPRIETAIRE",
    "GESTIONNAI": "GESTIONNAIRE",
    "CODE_POSTA": "CODE_POSTAL",

    # CABLE truncations
    "CODE_INFRA": "CODE_INFRA",
    "TYPE_CABLE": "TYPE_CABLE",
    "TYPE_FIBRE": "TYPE_FIBRE",
    "NB_FIBRE_D": "NB_FIBRE_DISP",
    "TYPE_PROP": "TYPE_PROP",
    "REF_PRODUI": "REF_PRODUIT",

    # PTECH truncations
    "HAUTEUR_AP": "HAUTEUR_APPUI",
    "TYPE_APPUI": "TYPE_APPUI",
    "EFFORT_APP": "EFFORT_APPUI",
    "NB_BOITIER": "NB_BOITIERS",

    # INFRASTRUCTURE truncations
    "COMPOSITI": "COMPOSITION",
    "TYPE_LOG": "TYPE_LOG",

    # SITE truncations
    "REF_PRODUI": "REF_PRODUIT",
    "MODE_POSE": "MODE_POSE",

    # ZNRO / ZPM truncations
    "NB_PRISES": "NB_PRISES",
    "REF_SRO": "REF_SRO",
    "REF_NRO": "REF_NRO",

    # IMB truncations
    "NUMERO_VOI": "NUMERO_VOIE",
    "TYPE_VOIE": "TYPE_VOIE",
    "TYPE_BATIM": "TYPE_BATIMENT",
    "TYPE_CLIEN": "TYPE_CLIENT",
    "RACCORDEME": "RACCORDEMENT",
    "COL_MONTAN": "COL_MONTANTE",
    "SOUS_SOL_C": "SOUS_SOL_COMMUN",
    "NB_LOC_RES": "NB_LOC_RES",
    "NB_LOC_PRO": "NB_LOC_PRO",
    "NB_LOC_TOT": "NB_LOC_TOT",
    "NB_ETAGE": "NB_ETAGE",
    "BPE_CODE": "BPE_CODE",

    # Universal
    "REF_PLAQUE": "REF_PLAQUE",
    "REF_PM": "REF_PM",
    "ADRESSSE": "ADRESSSE",
    "FABRIQUANT": "FABRIQUANT",
    "ORIGINE": "ORIGINE",
    "EXTREMITE": "EXTREMITE",
    "LONGUEUR": "LONGUEUR",
    "CAPACITE": "CAPACITE",
    "DIAMETRE": "DIAMETRE",
    "COMMENT": "COMMENT",
    "STATUT": "STATUT",
    "VILLE": "VILLE",
    "COMMUNE": "COMMUNE",
    "REGION": "REGION",
    "PROVINCE": "PROVINCE",
}

# ── 6. NEGATIVE EVIDENCE LAYERS ────────────────────────────────────────────────
# DWG layers that must never be classified into FTTH feature classes.
# Applies at Agent 6 Tier-1 classification gate.

NEGATIVE_EVIDENCE_LAYERS = {
    "APPROVAL",
    "LEGEND",
    "CARTOUCHE",
    "TITLE",
    "LEGENDE",
    "DEFPOINTS",
    "NORTH ARROW",
    "SCALE BAR",
    "GRID",
    "Base Map",
    "BASIC MAP",
    "BOM",
    "outline",
    "BOEDER",
    "mainlayer",
    "Fenetres ARCHICAD",
    "Portes ARCHICAD",
    "CARLAGE",
    "POMPIER",
    "fenêtres",
    "MURS 2",
}

# ── 7. LAYER PATTERN MAP ──────────────────────────────────────────────────────
# Tier-1 DWG layer regex → FC name + geometry type (from Agent 6).
# Applied case-insensitive against DWG layer names.

LAYER_PATTERN_MAP = [
    # BOITE — splice closures, distribution points, terminals (MUST be before CABLE
    # to prevent FAT/FO layer names from matching CABLE's FO pattern first)
    (r"(?i).*box.*|.*slimbox.*|.*blackbox.*|.*closure.*|.*fdt.*|.*fat\b|.*cto.*"
     r"|.*nap.*|.*dp\b|.*mdu.*|.*sdu.*|.*ont.*|.*pedestal.*|.*cabinet.*"
     r"|.*splice.*|.*splitter.*|.*spliter.*|.*patch.*|.*panel.*|.*terminal.*"
     r"|.*otb.*|.*fsc.*|.*boite.*|.*hw-fat.*",
     "BOITE", "Point"),
    # PTECH — poles, chambers, manholes, handholes, anchors
    (r"(?i).*pole.*|.*poteau.*|.*chamber.*|.*chambre.*|.*manhole.*|.*handhole.*"
     r"|.*anchor.*|.*guy\b|.*vault.*|.*trench.*|.*ptech.*"
     r"|.*gaine\s*technique.*|.*gc\s|.*appui.*|.*ancrage.*"
     r"|.*hw-handhole.*|.*iam\s*mh.*",
     "PTECH", "Point"),
    # CABLE — optical fibre / copper cable (English + French bilingual)
    # NOTE: FO patterns restricted to avoid matching FAT/FO layer names
    (r"(?i).*cable.*|.*fib[er]*e.*|.*feeder.*|.*trunk.*"
     r"|.*distribution.*|.*drop.*|.*riser.*|.*lateral.*|.*backbone.*|.*access.*"
     r"|.*span\s*cable.*|.*micro\s*cable.*|.*loose\s*cable.*"
     r"|.*sling\s*wire.*|.*suspension\s*wire.*"
     r"|.*fo\s*\d+\s*core.*|.*fo\s*cable.*",
     "CABLE", "LineString"),
    # IMB — buildings, premises, homes
    (r"(?i).*building.*|.*batiment.*|.*premise.*|.*house.*|.*home\s*number.*"
     r"|.*home\s*pass.*|.*hp\s*cover.*|.*unit.*|.*apartment.*|.*office.*"
     r"|.*mdu.*|.*sdu.*|.*imb.*|.*property.*|.*address.*"
     r"|.*customer.*|.*subscriber.*|.*logement.*|.*maison.*|.*villa.*"
     r"|.*immeuble.*|.*residence.*|.*etik.*",
     "IMB", "Polygon"),
    # INFRASTRUCTURE — ducts, conduits, trenches
    (r"(?i).*duct.*|.*conduit.*|.*pipe.*|.*trench.*|.*infra.*"
     r"|.*pathway.*|.*route.*|.*buried.*|.*underground.*|.*aerial.*"
     r"|.*fourreau.*|.*adduction.*|.*branchement.*|.*raccordement.*"
     r"|.*gaine.*|.*new\s*duct.*",
     "INFRASTRUCTURE", "LineString"),
    # SITE — exchanges, nodes, hubs, shelters
    (r"(?i).*site.*|.*nro.*|.*pm\b|.*exchange.*|.*node.*|.*hub.*"
     r"|.*pop\b|.*co\b|.*shelter.*|.*cabinet.*|.*location.*"
     r"|.*olt.*|.*ftts.*|.*local.*tech.*",
     "SITE", "Point"),
    # ZNRO — NRO coverage zones
    (r"(?i).*znro.*|.*zone.*nro.*|.*olt.*zone.*|.*exchange.*zone.*"
     r"|.*coverage.*|.*service.*area.*",
     "ZNRO", "Polygon"),
    # ZPM — PM / SRO coverage zones
    (r"(?i).*zpm.*|.*zone.*pm.*|.*zone.*sro.*|.*distribution.*zone.*"
     r"|.*service.*zone.*|.*fat.*area.*|.*boundary.*fat.*",
     "ZPM", "Polygon"),
    # Generic fallbacks (lower confidence)
    (r"(?i)^line$", "CABLE", "LineString"),
    (r"(?i).*service\s*core.*|.*expansion\s*core.*|.*moniter\s*core.*",
     "INFRASTRUCTURE", "LineString"),
    (r"(?i).*sling.*wire.*|.*suspension.*wire.*|.*span.*sling.*",
     "CABLE", "LineString"),
    (r"(?i)^eu$|^go\d*$|^go$", "PTECH", "Point"),
    (r"(?i)^pln$|^telkom$", "SITE", "Point"),
    (r"(?i).*ftts.*site.*", "SITE", "Point"),
    (r"(?i)^text$|.*etik.*", "IMB", "Point"),
]

# ── 8. DOMAIN VOCABULARIES ────────────────────────────────────────────────────
# Hardcoded domain value sets for all enum fields.
# D7: All values normalized to UPPERCASE for case-insensitive comparison.

DOMAIN_VOCABULARIES = {
    "STATUT": {
        "DEPLOYE",
        "EN COURS DE DEPLOIEMENT",
        "EN PROJET",
    },
    "TYPE_CABLE": {
        "TRANSPORT",
        "DISTRIBUTION",
        "RACCORDEMENT",
        "VERTICALITE",
        "COLLECTE",
    },
    "TYPE_FIBRE": {
        "G652", "G652A", "G652B", "G652C", "G652D",
        "G657", "G657A", "G657A1", "G657A2", "G657A3",
        "G657B", "G657B1", "G657B2", "G657B3",
    },
    "MODE_POSE_CABLE": {
        "SOUTERRAIN",
        "AERIEN",
        "FACADE",
        "IMMEUBLE",
        "COLONNE MONTANTE",
    },
    "MODE_POSE_BOITE": {
        "FACADE",
        "CHAMBRE",
        "AERIEN",
    },
    "BOITE_TYPE": {
        "BPE",
        "PBO",
        "BPI",
        "PTO",
    },
    "SITE_TYPE": {
        "NRO",
        "PM",
        "ARMOIRE DE RUE",
        "BATIMENT",
        "LOCAL TECHNIQUE",
        "SHELTER",
    },
    "PTECH_TYPE": {
        "APPUI",
        "CHAMBRE",
        "ANCRAGE FACADE",
        "IMMEUBLE",
        "AUTRE",
    },
    "TYPE_LOG": {
        "TRANSPORT",
        "DISTRIBUTION",
        "RACCORDEMENT",
    },
    "IMB_TYPE_BATIMENT": {
        "VILLA",
        "BATIMENT",
        "BATIMENT R+1",
        "BATIMENT R+2",
        "BATIMENT R+3",
        "IMMEUBLE",
        "IMMEUBLE COLLECTIF",
        "COMMERCE",
        "ENTREPOT",
        "ENTREPRISE",
        "USINE",
        "BATIMENT PUBLIC",
        "BATIMENT RELIGIEUX",
        "EQUIPEMENT SPORTIF",
        "ETABLISSEMENT PRIVE",
        "EXPLOITATION AGRICOLE",
        "EOLIENNE",
        "POSTE ELECTRIQUE",
        "PYLONE",
        "STATION METEO",
        "STATION POMPAGE",
    },
    "IMB_TYPE_CLIENT": {
        "RESIDENTIEL",
        "PROFESSIONNEL",
        "ADMINISTRATION",
        "ENTREPRISE",
        "OPERATEUR",
    },
    "IMB_RACCORDEMENT": {
        "SOUTERRAIN",
        "FACADE",
        "AERIEN",
        "COLONNE MONTANTE",
    },
    "INFRASTRUCTURE_TYPE": {
        "AERIEN",
        "SOUTERRAIN",
    },
    "TYPE_STRUCTURE": {
        "TRANSPORT",
        "DISTRIBUTION",
    },
}

# Mapping: layer.field → domain vocabulary key
FIELD_DOMAIN_MAP = {
    "BOITE.STATUT": "STATUT",
    "BOITE.TYPE": "BOITE_TYPE",
    "BOITE.MODE_POSE": "MODE_POSE_BOITE",
    "BOITE.TYPE_STRUCTURE": "TYPE_STRUCTURE",
    "CABLE.STATUT": "STATUT",
    "CABLE.TYPE_CABLE": "TYPE_CABLE",
    "CABLE.MODE_POSE": "MODE_POSE_CABLE",
    "CABLE.TYPE_FIBRE": "TYPE_FIBRE",
    "PTECH.STATUT": "STATUT",
    "PTECH.TYPE": "PTECH_TYPE",
    "INFRASTRUCTURE.STATUT": "STATUT",
    "INFRASTRUCTURE.TYPE": "INFRASTRUCTURE_TYPE",
    "INFRASTRUCTURE.TYPE_LOG": "TYPE_LOG",
    "SITE.STATUT": "STATUT",
    "SITE.TYPE": "SITE_TYPE",
    "ZNRO.STATUT": "STATUT",
    "ZPM.STATUT": "STATUT",
    "IMB.STATUT": "STATUT",
    "IMB.TYPE_BATIMENT": "IMB_TYPE_BATIMENT",
    "IMB.TYPE_CLIENT": "IMB_TYPE_CLIENT",
    "IMB.RACCORDEMENT": "IMB_RACCORDEMENT",
}

# ── 9. FOREIGN KEY DEPENDENCY GRAPH ────────────────────────────────────────────

FK_DEPENDENCY_GRAPH = {
    "FK1": {
        "source_layer": "CABLE",
        "source_field": "CODE_INFRA",
        "target_layer": "INFRASTRUCTURE",
        "target_field": "CODE",
        "null_allowed": True,
        "severity": "E",
        "description": "CABLE.CODE_INFRA → INFRASTRUCTURE.CODE",
    },
    "FK2": {
        "source_layer": "BOITE",
        "source_field": "REF_NRO",
        "target_layer": "SITE",
        "target_field": "CODE",
        "target_filter": {"TYPE": "NRO"},
        "null_allowed": True,
        "severity": "W",
        "description": "BOITE.REF_NRO → SITE.CODE (where TYPE=NRO)",
    },
    "FK3": {
        "source_layer": "BOITE",
        "source_field": "REF_PM",
        "target_layer": "SITE",
        "target_field": "CODE",
        "target_filter": {"TYPE": "PM"},
        "null_allowed": False,
        "severity": "E",
        "description": "BOITE.REF_PM → SITE.CODE (where TYPE=PM)",
    },
    "FK4": {
        "source_layer": "CABLE",
        "source_field": "REF_PM",
        "target_layer": "SITE",
        "target_field": "CODE",
        "target_filter": {"TYPE": "PM"},
        "null_allowed": False,
        "severity": "E",
        "description": "CABLE.REF_PM → SITE.CODE (where TYPE=PM)",
    },
    "FK5": {
        "source_layer": "ZPM",
        "source_field": "REF_NRO",
        "target_layer": "ZNRO",
        "target_field": "REF_NRO",
        "null_allowed": False,
        "severity": "E",
        "description": "ZPM.REF_NRO → ZNRO.REF_NRO",
    },
    "FK6": {
        "source_layer": "SITE",
        "source_field": "REF_NRO",
        "target_layer": "ZNRO",
        "target_field": "REF_NRO",
        "null_allowed": False,
        "severity": "E",
        "description": "SITE.REF_NRO → ZNRO.REF_NRO (for PM-type sites)",
    },
    "FK7": {
        "source_layer": "CABLE",
        "source_field": "ORIGINE",
        "target_layer": ["BOITE", "SITE"],
        "target_field": "CODE",
        "null_allowed": False,
        "severity": "E",
        "description": "CABLE.ORIGINE → BOITE.CODE or SITE.CODE",
    },
    "FK8": {
        "source_layer": "CABLE",
        "source_field": "EXTREMITE",
        "target_layer": ["BOITE", "SITE"],
        "target_field": "CODE",
        "null_allowed": False,
        "severity": "E",
        "description": "CABLE.EXTREMITE → BOITE.CODE or SITE.CODE",
    },
}

# ── 10. VERIFICATION RULES ────────────────────────────────────────────────────
# Structured config for all 7 rule groups, sourced from VERIFICATION_RULE.csv
# and FTTH_GIS_Technical_Standards.md Part III.

VERIFICATION_RULES = [
    # ── Rule Group 1: File Integrity ─────────────────────────────────────────
    {
        "rule_id": "1.1",
        "rule_group": 1,
        "rule_group_name": "File Integrity Checks",
        "severity": "C",
        "description": "All 8 layers present in output: BOITE, CABLE, PTECH, INFRASTRUCTURE, SITE, ZNRO, ZPM, IMB",
        "layer": None,
        "fields": [],
        "check_function": "check_1_1_layer_presence",
    },
    {
        "rule_id": "1.2",
        "rule_group": 1,
        "rule_group_name": "File Integrity Checks",
        "severity": "E",
        "description": "IMB layer → Point geometry; name ends with _IMB or IMB",
        "layer": "IMB",
        "fields": [],
        "check_function": "check_1_2_imb_naming",
    },
    {
        "rule_id": "1.3",
        "rule_group": 1,
        "rule_group_name": "File Integrity Checks",
        "severity": "E",
        "description": "SITE layer → Point geometry; name ends with _SITE or SITE",
        "layer": "SITE",
        "fields": [],
        "check_function": "check_1_3_site_naming",
    },
    {
        "rule_id": "1.4",
        "rule_group": 1,
        "rule_group_name": "File Integrity Checks",
        "severity": "E",
        "description": "BOITE layer → Point geometry; name ends with _BOITE or BOITE",
        "layer": "BOITE",
        "fields": [],
        "check_function": "check_1_4_boite_naming",
    },
    {
        "rule_id": "1.5",
        "rule_group": 1,
        "rule_group_name": "File Integrity Checks",
        "severity": "E",
        "description": "CABLE layer → LineString geometry; name ends with _CABLE or CABLE",
        "layer": "CABLE",
        "fields": [],
        "check_function": "check_1_5_cable_naming",
    },
    {
        "rule_id": "1.6",
        "rule_group": 1,
        "rule_group_name": "File Integrity Checks",
        "severity": "E",
        "description": "PTECH layer → Point geometry; name ends with _PTECH or PTECH",
        "layer": "PTECH",
        "fields": [],
        "check_function": "check_1_6_ptech_naming",
    },
    {
        "rule_id": "1.7",
        "rule_group": 1,
        "rule_group_name": "File Integrity Checks",
        "severity": "E",
        "description": "INFRASTRUCTURE layer → LineString; name ends with _INFRASTRUCTURE",
        "layer": "INFRASTRUCTURE",
        "fields": [],
        "check_function": "check_1_7_infrastructure_naming",
    },
    {
        "rule_id": "1.8",
        "rule_group": 1,
        "rule_group_name": "File Integrity Checks",
        "severity": "E",
        "description": "ZNRO layer → Polygon; name ends with _ZNRO or ZNRO",
        "layer": "ZNRO",
        "fields": [],
        "check_function": "check_1_8_znro_naming",
    },
    {
        "rule_id": "1.9",
        "rule_group": 1,
        "rule_group_name": "File Integrity Checks",
        "severity": "E",
        "description": "ZPM layer → Polygon; name ends with _ZPM or ZPM",
        "layer": "ZPM",
        "fields": [],
        "check_function": "check_1_9_zpm_naming",
    },

    # ── Rule Group 2: CRS Consistency ────────────────────────────────────────
    {
        "rule_id": "2.0",
        "rule_group": 2,
        "rule_group_name": "CRS Consistency Check",
        "severity": "C",
        "description": "All layers use EPSG:4326 (WGS84). QGIS project CRS: EPSG:3857 for OSM display.",
        "layer": None,
        "fields": [],
        "check_function": "check_2_0_crs_consistency",
    },

    # ── Rule Group 3: Empty Layer ────────────────────────────────────────────
    {
        "rule_id": "3.0",
        "rule_group": 3,
        "rule_group_name": "Empty Layer Check",
        "severity": "C",
        "description": "No layer may be empty — each of the 8 layers must have at least 1 feature.",
        "layer": None,
        "fields": [],
        "check_function": "check_3_0_empty_layer",
    },

    # ── Rule Group 4: Field Existence and Non-Null ────────────────────────────
    {
        "rule_id": "4.1",
        "rule_group": 4,
        "rule_group_name": "Field Existence and Non-Null Checks",
        "severity": "E",
        "description": "IMB mandatory fields present AND non-null. Excludes CODE_VOIE (D5: does not exist in schema).",
        "layer": "IMB",
        "fields": IMB["mandatory_fields"],
        "check_function": "check_4_1_imb_fields",
    },
    {
        "rule_id": "4.2_IMB",
        "rule_group": 4,
        "rule_group_name": "Field Existence and Non-Null Checks",
        "severity": "E",
        "description": "CODE must be unique within IMB layer.",
        "layer": "IMB",
        "fields": ["CODE"],
        "check_function": "check_4_code_uniqueness",
    },
    {
        "rule_id": "4.3",
        "rule_group": 4,
        "rule_group_name": "Field Existence and Non-Null Checks",
        "severity": "E",
        "description": "BOITE mandatory fields present AND non-null.",
        "layer": "BOITE",
        "fields": BOITE["mandatory_fields"],
        "check_function": "check_4_3_boite_fields",
    },
    {
        "rule_id": "4.4_BOITE",
        "rule_group": 4,
        "rule_group_name": "Field Existence and Non-Null Checks",
        "severity": "E",
        "description": "CODE must be unique within BOITE layer.",
        "layer": "BOITE",
        "fields": ["CODE"],
        "check_function": "check_4_code_uniqueness",
    },
    {
        "rule_id": "4.5",
        "rule_group": 4,
        "rule_group_name": "Field Existence and Non-Null Checks",
        "severity": "E",
        "description": "CABLE mandatory fields present AND non-null. D4: deduplicated CODE field.",
        "layer": "CABLE",
        "fields": CABLE["mandatory_fields"],
        "check_function": "check_4_5_cable_fields",
    },
    {
        "rule_id": "4.6_CABLE",
        "rule_group": 4,
        "rule_group_name": "Field Existence and Non-Null Checks",
        "severity": "E",
        "description": "CODE must be unique within CABLE layer.",
        "layer": "CABLE",
        "fields": ["CODE"],
        "check_function": "check_4_code_uniqueness",
    },
    {
        "rule_id": "4.7",
        "rule_group": 4,
        "rule_group_name": "Field Existence and Non-Null Checks",
        "severity": "E",
        "description": "PTECH mandatory fields present AND non-null. D4: deduplicated CODE field.",
        "layer": "PTECH",
        "fields": PTECH["mandatory_fields"],
        "check_function": "check_4_7_ptech_fields",
    },
    {
        "rule_id": "4.8_PTECH",
        "rule_group": 4,
        "rule_group_name": "Field Existence and Non-Null Checks",
        "severity": "E",
        "description": "CODE must be unique within PTECH layer.",
        "layer": "PTECH",
        "fields": ["CODE"],
        "check_function": "check_4_code_uniqueness",
    },
    {
        "rule_id": "4.9",
        "rule_group": 4,
        "rule_group_name": "Field Existence and Non-Null Checks",
        "severity": "E",
        "description": "INFRASTRUCTURE mandatory fields present AND non-null. D4: deduplicated CODE field.",
        "layer": "INFRASTRUCTURE",
        "fields": INFRASTRUCTURE_FC["mandatory_fields"],
        "check_function": "check_4_9_infrastructure_fields",
    },
    {
        "rule_id": "4.10_INFRA",
        "rule_group": 4,
        "rule_group_name": "Field Existence and Non-Null Checks",
        "severity": "E",
        "description": "CODE must be unique within INFRASTRUCTURE layer.",
        "layer": "INFRASTRUCTURE",
        "fields": ["CODE"],
        "check_function": "check_4_code_uniqueness",
    },
    {
        "rule_id": "4.11",
        "rule_group": 4,
        "rule_group_name": "Field Existence and Non-Null Checks",
        "severity": "E",
        "description": "ZPM mandatory fields present AND non-null. D1: ZPM uses REF_SRO not REF_PM.",
        "layer": "ZPM",
        "fields": ZPM["mandatory_fields"],
        "check_function": "check_4_11_zpm_fields",
    },
    {
        "rule_id": "4.12_ZPM",
        "rule_group": 4,
        "rule_group_name": "Field Existence and Non-Null Checks",
        "severity": "E",
        "description": "CODE must be unique within ZPM layer.",
        "layer": "ZPM",
        "fields": ["CODE"],
        "check_function": "check_4_code_uniqueness",
    },
    {
        "rule_id": "4.13",
        "rule_group": 4,
        "rule_group_name": "Field Existence and Non-Null Checks",
        "severity": "E",
        "description": "ZNRO mandatory fields present AND non-null.",
        "layer": "ZNRO",
        "fields": ZNRO["mandatory_fields"],
        "check_function": "check_4_13_znro_fields",
    },
    {
        "rule_id": "4.14_ZNRO",
        "rule_group": 4,
        "rule_group_name": "Field Existence and Non-Null Checks",
        "severity": "E",
        "description": "CODE must be unique within ZNRO layer.",
        "layer": "ZNRO",
        "fields": ["CODE"],
        "check_function": "check_4_code_uniqueness",
    },
    {
        "rule_id": "4.15",
        "rule_group": 4,
        "rule_group_name": "Field Existence and Non-Null Checks",
        "severity": "E",
        "description": "SITE mandatory fields present AND non-null.",
        "layer": "SITE",
        "fields": SITE["mandatory_fields"],
        "check_function": "check_4_15_site_fields",
    },
    {
        "rule_id": "4.16_SITE",
        "rule_group": 4,
        "rule_group_name": "Field Existence and Non-Null Checks",
        "severity": "E",
        "description": "CODE must be unique within SITE layer.",
        "layer": "SITE",
        "fields": ["CODE"],
        "check_function": "check_4_code_uniqueness",
    },

    # ── Rule Group 5: Isolation / Referential Integrity ──────────────────────
    {
        "rule_id": "5.1",
        "rule_group": 5,
        "rule_group_name": "Isolation (Referential Integrity) Checks",
        "severity": "E",
        "description": "SITE(TYPE=PM) and ZPM bidirectional isolation: every PM SITE has a matching ZPM entry (SITE.CODE = ZPM.CODE), and vice versa.",
        "layer": ["SITE", "ZPM"],
        "fields": ["SITE.TYPE", "SITE.CODE", "ZPM.CODE"],
        "check_function": "check_5_1_site_zpm_isolation",
    },
    {
        "rule_id": "5.2",
        "rule_group": 5,
        "rule_group_name": "Isolation (Referential Integrity) Checks",
        "severity": "E",
        "description": "SITE(PM) ↔ BOITE(PBO) master-slave isolation: every PBO BOITE has REF_PM → valid PM SITE; every PM SITE has ≥1 PBO BOITE.",
        "layer": ["SITE", "BOITE"],
        "fields": ["BOITE.REF_PM", "SITE.CODE", "BOITE.TYPE"],
        "check_function": "check_5_2_site_boite_isolation",
    },
    {
        "rule_id": "5.3",
        "rule_group": 5,
        "rule_group_name": "Isolation (Referential Integrity) Checks",
        "severity": "E",
        "description": "SITE(PM) ↔ CABLE(DISTRIBUTION) master-slave isolation: every DISTRIBUTION cable references valid PM SITE via REF_PM.",
        "layer": ["SITE", "CABLE"],
        "fields": ["CABLE.REF_PM", "SITE.CODE", "CABLE.TYPE_CABLE"],
        "check_function": "check_5_3_site_cable_isolation",
    },
    {
        "rule_id": "5.4",
        "rule_group": 5,
        "rule_group_name": "Isolation (Referential Integrity) Checks",
        "severity": "E",
        "description": "CABLE ORIGINE/EXTREMITE ↔ BOITE/SITE bidirectional isolation (4 sub-checks: forward check, reverse check A/B, all endpoints resolved).",
        "layer": ["CABLE", "BOITE", "SITE"],
        "fields": ["CABLE.ORIGINE", "CABLE.EXTREMITE", "BOITE.CODE", "BOITE.TYPE", "SITE.CODE", "SITE.TYPE"],
        "check_function": "check_5_4_cable_endpoint_isolation",
        "sub_checks": ["5.4.1", "5.4.2", "5.4.3"],
    },

    # ── Rule Group 6: Geometric Checks ───────────────────────────────────────
    {
        "rule_id": "6.1",
        "rule_group": 6,
        "rule_group_name": "Geometric Checks",
        "severity": "E",
        "description": "ZNRO polygons must not overlap within same layer. Shared edges (tangent) are permitted.",
        "layer": "ZNRO",
        "fields": [],
        "check_function": "check_6_1_znro_no_overlap",
    },
    {
        "rule_id": "6.2",
        "rule_group": 6,
        "rule_group_name": "Geometric Checks",
        "severity": "E",
        "description": "ZPM polygons must not overlap within same layer. Shared edges (tangent) are permitted.",
        "layer": "ZPM",
        "fields": [],
        "check_function": "check_6_2_zpm_no_overlap",
    },
    {
        "rule_id": "6.3",
        "rule_group": 6,
        "rule_group_name": "Geometric Checks",
        "severity": "E",
        "description": "SITE(TYPE=PM) point must fall within corresponding ZPM polygon (SITE.CODE = ZPM.CODE).",
        "layer": ["SITE", "ZPM"],
        "fields": ["SITE.TYPE", "SITE.CODE", "ZPM.CODE"],
        "check_function": "check_6_3_site_in_zpm",
    },
    {
        "rule_id": "6.4",
        "rule_group": 6,
        "rule_group_name": "Geometric Checks",
        "severity": "E",
        "description": "BOITE(TYPE=PBO) point must fall within ZPM polygon of parent PM (BOITE.REF_PM = SITE.CODE = ZPM.CODE).",
        "layer": ["BOITE", "SITE", "ZPM"],
        "fields": ["BOITE.REF_PM", "BOITE.TYPE", "SITE.CODE", "SITE.TYPE", "ZPM.CODE"],
        "check_function": "check_6_4_boite_in_zpm",
    },
    {
        "rule_id": "6.5",
        "rule_group": 6,
        "rule_group_name": "Geometric Checks",
        "severity": "E",
        "description": "CABLE(TYPE=DISTRIBUTION): all endpoints and vertices must be within its parent ZPM polygon (CABLE.REF_PM = SITE.CODE = ZPM.CODE).",
        "layer": ["CABLE", "SITE", "ZPM"],
        "fields": ["CABLE.REF_PM", "CABLE.TYPE_CABLE", "SITE.CODE", "ZPM.CODE"],
        "check_function": "check_6_5_cable_in_zpm",
    },
    {
        "rule_id": "6.6",
        "rule_group": 6,
        "rule_group_name": "Geometric Checks",
        "severity": "E",
        "description": "CABLE endpoints connected to BOITE/SITE. 6.6a: ORIGINE ≠ EXTREMITE (no self-loops). 6.6b: endpoint geometry coincides with resolved node within 0.0001°.",
        "layer": ["CABLE", "BOITE", "SITE"],
        "fields": ["CABLE.ORIGINE", "CABLE.EXTREMITE", "BOITE.CODE", "SITE.CODE"],
        "check_function": "check_6_6_cable_endpoint_coincidence",
        "sub_checks": ["6.6a", "6.6b"],
    },

    # ── Rule Group 7: Data Validation ────────────────────────────────────────
    {
        "rule_id": "7.1",
        "rule_group": 7,
        "rule_group_name": "Data Validation Checks",
        "severity": "E",
        "description": "For each PBO: NB_FIBRE_UTIL ≤ CAPACITE. A PBO cannot serve more fibres than its physical capacity.",
        "layer": "BOITE",
        "fields": ["BOITE.TYPE", "BOITE.NB_FIBRE_UTIL", "BOITE.CAPACITE"],
        "check_function": "check_7_1_pbo_capacity",
    },
    {
        "rule_id": "7.2",
        "rule_group": 7,
        "rule_group_name": "Data Validation Checks",
        "severity": "E",
        "description": "Per PM: SUM(PBO CAPACITE) ≤ SUM(DISTRIBUTION cable CAPACITE originating from PM).",
        "layer": ["SITE", "BOITE", "CABLE"],
        "fields": ["SITE.CODE", "SITE.TYPE", "BOITE.TYPE", "BOITE.CAPACITE", "BOITE.REF_PM", "CABLE.TYPE_CABLE", "CABLE.CAPACITE", "CABLE.ORIGINE"],
        "check_function": "check_7_2_pm_port_balance",
    },
]

# ── Rule groups lookup ────────────────────────────────────────────────────────

RULE_GROUPS = {
    1: "File Integrity Checks",
    2: "CRS Consistency Check",
    3: "Empty Layer Check",
    4: "Field Existence and Non-Null Checks",
    5: "Isolation (Referential Integrity) Checks",
    6: "Geometric Checks",
    7: "Data Validation Checks",
}

# ── Convenience: rules indexed by rule_id ─────────────────────────────────────

VERIFICATION_RULES_BY_ID = {r["rule_id"]: r for r in VERIFICATION_RULES}

# ── Severity threshold: features with confidence below this go to fc_misc ──────

SCHEMA_CONFIDENCE_THRESHOLD = 0.7

# ── Automation quality gates ──────────────────────────────────────────────────

QUALITY_GATES = {
    "automation_rate": 0.90,
    "coordinate_precision_degrees": 1e-5,
    "topology_violation_rate": 0.02,
    "semantic_coverage": 0.70,
    "schema_conformance": 0.80,
    "domain_compliance": 0.95,
    "referential_integrity_fk_rate": 0.01,
}

# ── CRS Configuration ─────────────────────────────────────────────────────────

CRS_DATA = "EPSG:4326"         # Authoritative geographic CRS for output data
CRS_QGIS_DISPLAY = "EPSG:3857" # QGIS project CRS for OSM tile alignment
